### ISSUE TITLE
Enhancement hexa

### ISSUE THREAD

**Issue by lolpowerluke** [Puv1s/ColorTooltips#2]
when I add a alpha value to the hex colors, it doesnt work (I tried it in vsc first to see if it was possible + to get the correct code)
![image](https://user-images.githubusercontent.com/47672899/131259474-f8da8e25-8ae3-4373-b1a6-6589f430f4d7.png)
the blue text is just because I changed the color with the editUsers plugin

**Comment by Puv1s** [comment]
That's HEXA and it's not supported currently.
Could be added in future

**Comment by lolpowerluke** [comment]
Alr, thx
